// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
export interface Button {
  label?: string;
  type: "" | "button" | "submit" | "reset";
  style?: "" | "primary" | "secondary" | "tertiary" | "borderless";
  disabled?: boolean;
  ariaLabel?: string;
  iconRight?: string;
  iconLeft?: string;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface Checkbox {
  name?: string;
  label?: string;
  ariaLabel?: string;
  disabled?: boolean;
  required?: boolean;
  component: "checkbox";
  _uid: string;
  [k: string]: unknown;
}

export interface Headline {
  tag: "" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  style: "" | "primary" | "secondary" | "tertiary" | "borderless";
  ariaLabel?: string;
  label?: string;
  bold?: boolean;
  component: "headline";
  _uid: string;
  [k: string]: unknown;
}

export interface Image {
  src: string;
  alt: string;
  width?: string;
  height?: string;
  fill?: boolean;
  quality?: string;
  loading: "" | "lazy" | "eager";
  aspectRatio?: string;
  objectFit?: "" | "cover" | "contain";
  sizes?: string;
  ariaLabel?: string;
  component: "image";
  _uid: string;
  [k: string]: unknown;
}

export interface Infomessage {
  ariaLabel?: string;
  label?: string;
  type: "" | "alert" | "warning" | "success";
  showIcon?: boolean;
  component: "infomessage";
  _uid: string;
  [k: string]: unknown;
}

export interface Intro {
  headline: Headline[];
  paragraph: Paragraph[];
  button: Button[];
  component: "intro";
  _uid: string;
  [k: string]: unknown;
}

export interface Link {
  label?: string;
  href: string;
  target?: "" | "_self" | "_blank";
  btn?: boolean;
  colored?: boolean;
  status: "" | "default" | "hover" | "focus" | "disabled";
  iconLeft?: string;
  iconRight?: string;
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | Button
    | Checkbox
    | Headline
    | Image
    | Infomessage
    | Intro
    | Link
    | Page
    | Paragraph
    | Radiobutton
    | Tooltip
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Paragraph {
  label?: string;
  bold?: boolean;
  style: "" | "primary" | "secondary" | "tertiary" | "borderless";
  ariaLabel?: string;
  component: "paragraph";
  _uid: string;
  [k: string]: unknown;
}

export interface Radiobutton {
  name?: string;
  value?: string;
  ariaLabel?: string;
  status: "" | "default" | "hover" | "focus" | "disabled" | "Error";
  component: "radiobutton";
  _uid: string;
  [k: string]: unknown;
}

export interface Tooltip {
  stlye: "" | "default" | "inverted";
  beak:
    | ""
    | "none"
    | "below-center"
    | "below-start"
    | "below-end"
    | "above-center"
    | "above-start"
    | "above-end"
    | "start-middle"
    | "start-top"
    | "start-bottom"
    | "end-middle"
    | "end-top"
    | "end-bottom";
  ariaLabel?: string;
  label?: string;
  component: "tooltip";
  _uid: string;
  [k: string]: unknown;
}
